apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlkyNWhkR2wyWlhKdk9tTnVZWFJwZG1WeWIwQXhOalU0IgoJCX0KCX0KfQo=
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
