apiVersion: v1
kind: Service
metadata:
  name: license-service
  namespace:  {{ .Release.Namespace }}
spec:
  type: {{ .Values.portal.server.licenseServer.service.type }}
  ports:
    - name: http
      port: {{ .Values.portal.server.licenseServer.service.port }}
      targetPort: {{ .Values.portal.server.licenseServer.service.targetPort }}
  selector:
    component: license-server