apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.portal.server.serviceAccountName }}
  namespace:  {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "cle.name" . }}-server
    {{- include "cle.labels" . | nindent 4 }}
