
name: deploy-pipeline
on:
  push:
    branches:
      - main

jobs:
  backend-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Debug
        run: aws s3 ls

      - name: Install helm s3 plugin
        run: helm plugin install https://github.com/hypnoglow/helm-s3.git --version v0.10.0

      - name: Adding helm repo
        run: helm repo add chaosnative s3://charts.chaosnative.com

      - name: Package helm
        run: helm package cle

      - name: Get Chart Version from Chart.yaml
        id: c_version
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.version' 'cle/Chart.yaml'

      - name: Push helm package to s3
        run: HELM_S3_MODE=3 helm s3 push --relative ./cle-${{ steps.c_version.outputs.result }}.tgz chaosnative --force
